blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Telegram Channel
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.