---
name: Lint with Gradle

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: nightly
          arguments: lintDebug
      - name: Upload lint report
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: lint-reports
          path: app/build/reports
