---
name: Release Build CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/release-build.yml
      - app/proguard-rules.pro

jobs:
  release-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: nightly
          arguments: assembleRelease

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk
